Use Linux device mapper to create writable snapshots

diff --git a/linux_snapshot/dattobd_create_filesystem_snapshot b/linux_snapshot/dattobd_create_filesystem_snapshot
--- a/linux_snapshot/dattobd_create_filesystem_snapshot
+++ b/linux_snapshot/dattobd_create_filesystem_snapshot
@@ -1,4 +1,4 @@
-#!/bin/sh
+!/bin/sh
 
 set -e
 
@@ -13,8 +13,8 @@ TYPE=$(df -T -P | egrep " ${SNAP_MOUNTPOINT}\$" | head -n 1 | tr -s " " | cut -d
 
 if [ "x$DEVICE" = "x" ]
 then
-        echo "Cannot get device for filesystem $SNAP_MOUNTPOINT"
-        exit 1
+    echo "Cannot get device for filesystem $SNAP_MOUNTPOINT"
+    exit 1
 fi
 
 echo "Snapshotting device $DEVICE via dattobd..."
@@ -28,11 +28,23 @@ done
 
 echo "Using /dev/datto$NUM..."
 
+sync
+
 dbdctl setup-snapshot "$DEVICE" "$SNAP_MOUNTPOINT/.datto_$SNAP_ID" $NUM
 
 echo $NUM > ${SNAP_DEST}-num
 
-echo "Mounting /dev/datto$NUM..."
+DEV_SIZE=`blockdev --getsize /dev/datto$NUM`
+
+truncate -s100M $SNAP_MOUNTPOINT/.overlay_$SNAP_ID
+
+LODEV=`losetup -f`
+
+losetup $LODEV $SNAP_MOUNTPOINT/.overlay_$SNAP_ID
+
+echo "0 $DEV_SIZE snapshot /dev/datto$NUM $LODEV N 8" | dmsetup create "wsnap-$SNAP_ID"
+
+echo "Mounting /dev/mapper/wsnap-$SNAP_ID..."
 
 mkdir -p $SNAP_DEST
 
@@ -40,16 +52,18 @@ MOUNTOPTS="ro"
 
 if [ $TYPE = "xfs" ]
 then
-        MOUNTOPTS="ro,nouuid,norecovery"
+    MOUNTOPTS="ro,nouuid"
 fi
 
-if ! mount -o $MOUNTOPTS /dev/datto$NUM $SNAP_DEST 
+if ! mount -o $MOUNTOPTS /dev/mapper/wsnap-$SNAP_ID $SNAP_DEST
 then
-	echo "Mounting filesystem failed"
-	rmdir "$SNAP_DEST"
-	rm "${SNAP_DEST}-num"
-	dbdctl destroy $NUM
-	exit 1
+    echo "Mounting filesystem failed"
+    rmdir "$SNAP_DEST"
+    rm "${SNAP_DEST}-num"
+    dmsetup remove "wsnap-$SNAP_ID"
+    rm $SNAP_MOUNTPOINT/.overlay_$SNAP_ID
+    dbdctl destroy $NUM
+    exit 1
 fi
 
 echo "SNAPSHOT=$SNAP_DEST"
diff --git a/linux_snapshot/dattobd_remove_filesystem_snapshot b/linux_snapshot/dattobd_remove_filesystem_snapshot
--- a/linux_snapshot/dattobd_remove_filesystem_snapshot
+++ b/linux_snapshot/dattobd_remove_filesystem_snapshot
@@ -9,33 +9,35 @@ SNAP_ORIG_PATH="$5"
 if ! test -e $SNAP_MOUNTPOINT
 then
     echo "Snapshot at $SNAP_MOUNTPOINT was already removed"
-	[ ! -e "$SNAP_ORIG_PATH/.datto_$SNAP_ID" ] || rm "$SNAP_ORIG_PATH/.datto_$SNAP_ID"
-	[ ! -e "${SNAP_MOUNTPOINT}-num" ] || rm "${SNAP_MOUNTPOINT}-num"
+    [ ! -e "$SNAP_ORIG_PATH/.datto_$SNAP_ID" ] || rm "$SNAP_ORIG_PATH/.datto_$SNAP_ID"
+    [ ! -e "${SNAP_MOUNTPOINT}-num" ] || rm "${SNAP_MOUNTPOINT}-num"
+    [ ! -e "$SNAP_ORIG_PATH/.overlay_$SNAP_ID" ] || rm "$SNAP_ORIG_PATH/.overlay_$SNAP_ID"
     exit 0
 fi
 
 if ! df -T -P | egrep " ${SNAP_MOUNTPOINT}\$" > /dev/null 2>&1
 then
-	echo "Snapshot is not mounted. Already removed"
-	rm "${SNAP_MOUNTPOINT}-num"
-	rmdir "${SNAP_MOUNTPOINT}"
-	[ ! -e "$SNAP_ORIG_PATH/.datto_$SNAP_ID" ] || rm "$SNAP_ORIG_PATH/.datto_$SNAP_ID"
-	exit 0
+    echo "Snapshot is not mounted. Already removed"
+    rm "${SNAP_MOUNTPOINT}-num"
+    rmdir "${SNAP_MOUNTPOINT}"
+    [ ! -e "$SNAP_ORIG_PATH/.datto_$SNAP_ID" ] || rm "$SNAP_ORIG_PATH/.datto_$SNAP_ID"
+    [ ! -e "$SNAP_ORIG_PATH/.overlay_$SNAP_ID" ] || rm "$SNAP_ORIG_PATH/.overlay_$SNAP_ID"
+    exit 0
 fi
 
 NUM=`cat "${SNAP_MOUNTPOINT}-num"` || true
 
 if [ "x$NUM" = "x" ]
 then
-        echo "Cannot get device number from ${SNAP_MOUNTPOINT}-num"
-        exit 1
+    echo "Cannot get device number from ${SNAP_MOUNTPOINT}-num"
+    exit 1
 fi
 
 echo "Unmounting /dev/datto$NUM at /mnt/urbackup_snaps/$SNAP_ID..."
 
 if ! umount /mnt/urbackup_snaps/$SNAP_ID
 then
-	echo "Unmounting /mnt/urbackup_snaps/$SNAP_ID failed. Retrying in 10s..."
+    echo "Unmounting /mnt/urbackup_snaps/$SNAP_ID failed. Retrying in 10s..."
     sleep 10
     umount /mnt/urbackup_snaps/$SNAP_ID
 fi
@@ -44,6 +46,16 @@ fi
 rm "${SNAP_MOUNTPOINT}-num"
 rmdir "${SNAP_MOUNTPOINT}"
 
+echo "Removing devicemapper snapshot..."
+
+dmsetup remove "wsnap-$SNAP_ID"
+
+rm "$SNAP_ORIG_PATH/.overlay_$SNAP_ID"
+
 echo "Destroying dattobd snapshot /dev/datto$NUM..."
 
 dbdctl destroy $NUM
+
+[ ! -e "$SNAP_ORIG_PATH/.datto_$SNAP_ID" ] || rm "$SNAP_ORIG_PATH/.datto_$SNAP_ID"
+
+exit 0
